### ISSUE TITLE
GIMKIT HAS ANTICHEAT

### ISSUE THREAD

**Issue by CTRLeo** [seanv999/GimKit#7]
when you run the command on GimKit it works as showed for a couple seconds but later shows a pop up saying you have been caught cheating and your teacher has been notified, and the host also gets a pop up that says "your name" HAS BEEN CAUGHT CHEATING". but the hack works either way

**Comment by seanv999** [comment]
I know thats why it says its patch, dont plan on updating it...BUT i might :)
